spring.application.name=cicd

# ─── Server ───────────────────────────────────────────────────────────────────
server.port=8080

# ─── PostgreSQL DataSource ────────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=Siraj
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ─── Actuator ─────────────────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info
